version: "3.8"
services: 
  
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    ports: 
      - "8080:8080"
      - "50000:50000"
    networks: 
      - jenkins-net
    volumes: 
      - jenkins-home:/var/jenkins_home

volumes: 
  jenkins-home:

networks: 
  jenkins-net: