FROM jenkins/jenkins:lts

LABEL maintainer="Chris Herrera <christian@christian.herrera.com>"
LABEL description="Containerized deployment of a Jenkins Master"
LABEL version="0.3.0"

VOLUME [ "/var/jenkins_home" ]

USER root
RUN apt-get update \
    && apt-get install -y \
       wget \
       apt-transport-https \
       software-properties-common

RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell

RUN git config --global http.sslverify false

# Groovy script to specify default number of executors
COPY /resources/executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

USER jenkins:jenkins

# JCasC plugin config directory
ENV CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc_configs/
RUN mkdir -p /var/jenkins_home/jcasc_configs/
COPY /resources/jcasc_configs/*.yml /var/jenkins_home/jcasc_configs/

# Install additional requested plugins from yaml file
COPY /resources/install_plugins.yml /tmp/jenkins_resources/
RUN jenkins-plugin-cli --plugin-file /tmp/jenkins_resources/install_plugins.yml

# 8080 for UI, 50000 for worker node connections 
EXPOSE 8080
EXPOSE 50000